<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fgc.Payments.Application\Fgc.Payments.Application.csproj" />
    <ProjectReference Include="..\Fgc.Payments.Domain\Fgc.Payments.Domain.csproj" />
  </ItemGroup>

</Project>
